language: python
python:
  - '3.8'

before script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Projet_08.settings.travis"

services:
  - postgresql

script:
  - sudo python3 ./manage.py test Auth.tests.test_base
  - sudo python3 ./manage.py test Nutella.tests.test_base

branches:
  only:
    - staging

