language: python

python:
- '3.8'

stages:
- test
- deploy

jobs:
  include:

  - stage: test
    before_script:
    - pip3 install -r requirements.txt
    
    services:
    - postgresql

    env: DJANGO_SETTINGS_MODULE="Projet_08.settings.travis"

    script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test Auth.tests.test_base
    - python3 manage.py test Nutella.tests.test_base

    branches: staging

  - stage: deploy
    addons:
      ssh_known_hosts: manu@ns329147.ip-37-187-116.eu

    before_script: []
    env:
    - USER="manu"
    script:  
    - openssl aes-256-cbc -K $encrypted_50d31c429933_key -iv $encrypted_50d31c429933_iv
      -in id_rsa.enc -out tmp/id_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/id_rsa
    - ssh-add /tmp/id_rsa
    - "pwd;mkdir travis_deploy;ls
    
    branches:
      only:
      - staging

