language: python

python:
- '3.8'

before_script:
- pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Projet_08.settings.travis"

services:
- postgresql

stages:
- test
- deploy

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test Auth.tests.test_base
  - python3 manage.py test Nutella.tests.test_base

jobs:
  include:
  - stage: deploy
    addons: 
      ssh_known_hosts: 37.187.116.21 
    before_script: []
    env:
    - USER="manu"
    script:
    - openssl aes-256-cbc -K $encrypted_50d31c429933_key -iv $encrypted_50d31c429933_iv
      -in id_rsa.enc -out id_rsa -d
    - ssh -i id_rsa ${USER}@${HOST_NAME} "ls;pwd"
    branches:
      only:
      - staging
      - master
